
### Fetch site metadata
GET http://localhost:5000/v1/meta?url=https://developar.in
Accept: application/json
Accept-Language: en

### Fetch site metadata
POST http://localhost:5000/v1/meta
Accept: application/json
Accept-Language: en
Content-Type: application/json

{
   "url": "https://developar.in",
   "props": ["title", "icon"]
}
